# Generated by Django 4.2.24 on 2025-09-27 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
