# Generated by Django 4.2.17 on 2024-12-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='widget',
            name='content',
            field=models.TextField(default='Widget Content'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(max_length=50),
        ),
    ]
