# Generated by Django 4.2.24 on 2025-09-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_food_product',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='product description not provided', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image not provideed', upload_to=''),
        ),
    ]
