# Generated by Django 4.2.24 on 2025-09-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_remove_product_tax_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='Image',
            new_name='image',
        ),
    ]
