# Generated by Django 4.2.24 on 2025-12-31 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_rename_image_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
